class CALB_protocol_prompt():
    Protocols_prompts = {
        1.0: # CALB_25_T25-1.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        2.0: # CALB_25_T25-2.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        3.0:  # CALB_35_B173.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        4.0:  # CALB_35_B174.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        5.0:  # CALB_35_B175.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        6.0:  # CALB_35_B222.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        7.0:  # CALB_35_B223.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        8.0:  # CALB_35_B224.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        9.0:  # CALB_35_B227.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        10.0:  # CALB_35_B228.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        11.0:  # CALB_35_B229.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        12.0:  # CALB_35_B230.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        13.0:  # CALB_35_B247.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        14.0:  # CALB_35_B248.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        15.0:  # CALB_35_B249.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        16.0:  # CALB_35_B250.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        17.0:  # CALB_45_B253.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 45 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        18.0:  # CALB_45_B254.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        19.0:  # CALB_45_B255.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        20.0:  # CALB_45_B256.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"The cycling consists of nine charging stages. In the first stage, the battery was charged at a constant current of 1.2 C to 3.83 V. "
            f"In the second stage, the battery was charged at a constant current of 1 C to 3.89 V. "
            f"In the third stage, the battery was charged at a constant current of 0.85 C to 3.95 V. "
            f"In the fourth stage, the battery was charged at a constant current of 0.75 C to 4.08 V. "
            f"In the fifth stage, the battery was charged at a constant current of 0.6 C to 4.11 V. "
            f"In the sixth stage, the battery was charged at a constant current of 0.5 C to 4.19 V. "
            f"In the seventh stage, the battery was charged at a constant current of 0.33 C to 4.24V. "
            f"In the eighth stage, the battery was charged at a constant current of 0.15 C to 4.35 V. "
            f"In the ninth stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.75 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        21.0:  # CALB_0_B182.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 0 degree Celsius. "
            f"The cycling consists of two charging stages. In the first stage, the battery was charged at a constant current of 1 C to 4.35 V. "
            f"In the second stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        22.0:  # CALB_0_B183.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 0 degree Celsius. "
            f"The cycling consists of two charging stages. In the first stage, the battery was charged at a constant current of 1 C to 4.35 V. "
            f"In the second stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        23.0:  # CALB_0_B184.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 0 degree Celsius. "
            f"The cycling consists of two charging stages. In the first stage, the battery was charged at a constant current of 1 C to 4.35 V. "
            f"In the second stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        24.0:  # CALB_0_B185.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 0 degree Celsius. "
            f"The cycling consists of two charging stages. In the first stage, the battery was charged at a constant current of 1 C to 4.35 V. "
            f"In the second stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        25.0:  # CALB_0_B187.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 0 degree Celsius. "
            f"The cycling consists of two charging stages. In the first stage, the battery was charged at a constant current of 1 C to 4.35 V. "
            f"In the second stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        26.0:  # CALB_0_B188.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 0 degree Celsius. "
            f"The cycling consists of two charging stages. In the first stage, the battery was charged at a constant current of 1 C to 4.35 V. "
            f"In the second stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        27.0:  # CALB_0_B189.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 0 degree Celsius. "
            f"The cycling consists of two charging stages. In the first stage, the battery was charged at a constant current of 1 C to 4.35 V. "
            f"In the second stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        28.0:  # CALB_0_B190.pkl
            f"Battery specifications: The data comes from a lithium-ion battery in a format of prismatic cell. "
            f"Its positive electrode is NCM. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is CALB Co., Ltd. "
            f"The nominal capacity is 58 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 0 degree Celsius. "
            f"The cycling consists of two charging stages. In the first stage, the battery was charged at a constant current of 1 C to 4.35 V. "
            f"In the second stage, the battery was charged at a constant voltage of 4.35V until the current is lower than 0.05C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
    }