class NA_protocol_prompt():
    Protocols_prompts = {
        1.0: # NA-ion_2850-30_20250117105706_DefaultGroup_45_2
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 30 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 2.9 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 2.9 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        2.0:  # NA-ion_4000-30_20250115110206_DefaultGroup_45_1
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 30 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 3.9 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 3.9 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        3.0:  # NA-ion_4500-30_20250114232539_DefaultGroup_45_8
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 30 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 4.5 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 4.5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        4.0:  # NA-ion_5000-25_20250115110326_DefaultGroup_38_1
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        5.0:  # NA-ion_5000-25_20250115110326_DefaultGroup_38_2
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        6.0:  # NA-ion_270040-1-1-64
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 2 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        7.0:  # NA-ion_270040-1-2-63
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        8.0:  # NA-ion_270040-1-3-62
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 4.2 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 4.2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        9.0:  # NA-ion_270040-1-4-61
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.8 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.8 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        10.0:  # NA-ion_270040-1-5-60
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        11.0:  # NA-ion_270040-1-6-59
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.7 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.7 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        12.0:  # NA-ion_270040-1-7-58
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.3 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        13.0:  # NA-ion_270040-1-8-57
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.8 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.8 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        14.0:  # NA-ion_270040-2-1-12--NA-ion_270040-2-8-12
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 3 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        15.0:  # NA-ion_270040-3-1-56
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 4.7 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 4.7 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        16.0:  # NA-ion_270040-3-2-55
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.1 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        17.0:  # NA-ion_270040-3-3-54
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.3 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        18.0:  # NA-ion_270040-3-4-53
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.3 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        19.0:  # NA-ion_270040-3-5-52
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        20.0:  # NA-ion_270040-3-6-51
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        21.0:  # NA-ion_270040-3-7-50
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 4.2 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 4.2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        22.0:  # NA-ion_270040-3-8-49
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        23.0:  # NA-ion_270040-4-1-48
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        24.0:  # NA-ion_270040-4-2-47
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 4.8 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 4.8 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        25.0:  # NA-ion_270040-4-3-46
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.8 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.8 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        26.0:  # NA-ion_270040-4-4-45
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.7 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.7 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        27.0:  # NA-ion_270040-4-5-44
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        28.0:  # NA-ion_270040-4-6-43
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 4.5 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 4.5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        29.0:  # NA-ion_270040-4-7-42
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        30.0:  # NA-ion_270040-4-8-41
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 2 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        31.0:  # NA-ion_270040-5-1-39
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.1 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        32.0:  # NA-ion_270040-5-2-38
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.1 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        33.0:  # NA-ion_270040-5-3-37
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.1 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        34.0:  # NA-ion_270040-5-4-36
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 2.5 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 2.5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        35.0:  # NA-ion_270040-5-5-35
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.7 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.7 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        36.0:  # NA-ion_270040-5-6-34
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.1 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        37.0:  # NA-ion_270040-5-7-33
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        38.0:  # NA-ion_270040-5-8-32
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 4.5 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 4.5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        39.0:  # NA-ion_270040-6-1-31
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        40.0:  # NA-ion_270040-6-2-30
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 4 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 4 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        41.0:  # NA-ion_270040-6-3-29
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        42.0:  # NA-ion_270040-6-4-28
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        43.0:  # NA-ion_270040-6-5-27
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 2 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        44.0:  # NA-ion_270040-6-6-26
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.7 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.7 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        45.0:  # NA-ion_270040-6-7-25
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        46.0:  # NA-ion_270040-6-8-24
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.7 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.7 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        47.0:  # NA-ion_270040-7-1-23
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 5.8 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 5.8 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        48.0:  # NA-ion_270040-7-2-22
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 4 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 4 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        49.0:  # NA-ion_270040-7-3-21
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        50.0:  # NA-ion_270040-8-1-20
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        51.0:  # NA-ion_270040-8-2-19
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        52.0:  # NA-ion_270040-8-3-18
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 2 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        53.0:  # NA-ion_270040-8-4-17
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        54.0:  # NA-ion_270040-8-5-16
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 3 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        55.0:  # NA-ion_270040-8-6-15
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        56.0:  # NA-ion_270040-8-7-14
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        57.0:  # NA-ion_270040-8-8-13
            f"Battery specifications: The data comes from a sodium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is not disclosed. "
            f"Its negative electrode is not disclosed. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Zhuhai Punashidai New Energy Co., Ltd. "
            f"The nominal capacity is 1 Ah. "
            f"Operating condition: "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 6 C until reaching 4 V, "
            f"The battery was then discharged at a constant current of 6 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
    }