class SNL_protocol_prompt():
    Protocols_prompts = {
        1.0:  # SNL_18650_LiFePO4_15C_0-100_0.5-2C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 15 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        2.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-0.5C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 0.5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        3.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-1C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        4.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-1C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        5.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-1C_c
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        6.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-1C_d
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        7.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-2C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        8.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-2C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        9.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-3C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        10.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-3C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        11.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-3C_c
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        12.0:  # SNL_18650_LiFePO4_25C_0-100_0.5-3C_d
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        13.0:  # SNL_18650_LiFePO4_35C_0-100_0.5-1C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        14.0:  # SNL_18650_LiFePO4_35C_0-100_0.5-1C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        15.0:  # SNL_18650_LiFePO4_35C_0-100_0.5-1C_c
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        16.0:  # SNL_18650_LiFePO4_35C_0-100_0.5-1C_d
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        17.0:  # SNL_18650_LiFePO4_35C_0-100_0.5-2C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        18.0:  # SNL_18650_LiFePO4_35C_0-100_0.5-2C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiFePO4. "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is A123 System. "
            f"The nominal capacity is 1.1 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.6 V, at which the battery was constant-voltage charged until the current dropped to 0.0455 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        19.0:  # SNL_18650_NCA_15C_0-100_0.5-1C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 15 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        20.0:  # SNL_18650_NCA_15C_0-100_0.5-1C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 15 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        21.0:  # SNL_18650_NCA_15C_0-100_0.5-2C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 15 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        22.0:  # SNL_18650_NCA_15C_0-100_0.5-2C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 15 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        23.0:  # SNL_18650_NCA_25C_0-100_0.5-0.5C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 0.5 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        24.0:  # SNL_18650_NCA_25C_0-100_0.5-0.5C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 0.5 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        25.0:  # SNL_18650_NCA_25C_0-100_0.5-1C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        26.0:  # SNL_18650_NCA_25C_0-100_0.5-1C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        27.0:  # SNL_18650_NCA_25C_0-100_0.5-1C_c
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        28.0:  # SNL_18650_NCA_25C_0-100_0.5-1C_d
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        29.0:  # SNL_18650_NCA_25C_0-100_0.5-2C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        30.0:  # SNL_18650_NCA_25C_0-100_0.5-2C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        31.0:  # SNL_18650_NCA_25C_20-80_0.5-0.5C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.98 V. "
            f"The battery was then discharged at a constant current of 0.5 C until reaching 2.7 V. "
            f"The cycling state-of-charge of this battery ranges from 20% to 80%.\n",
        32.0:  # SNL_18650_NCA_25C_20-80_0.5-0.5C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.98 V. "
            f"The battery was then discharged at a constant current of 0.5 C until reaching 2.7 V. "
            f"The cycling state-of-charge of this battery ranges from 20% to 80%.\n",
        33.0:  # SNL_18650_NCA_25C_20-80_0.5-0.5C_c
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.98 V. "
            f"The battery was then discharged at a constant current of 0.5 C until reaching 2.7 V. "
            f"The cycling state-of-charge of this battery ranges from 20% to 80%.\n",
        34.0:  # SNL_18650_NCA_25C_20-80_0.5-0.5C_d
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 3.98 V. "
            f"The battery was then discharged at a constant current of 0.5 C until reaching 2.7 V. "
            f"The cycling state-of-charge of this battery ranges from 20% to 80%.\n",
        35.0:  # SNL_18650_NCA_35C_0-100_0.5-1C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        36.0:  # SNL_18650_NCA_35C_0-100_0.5-1C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        37.0:  # SNL_18650_NCA_35C_0-100_0.5-1C_c
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        38.0:  # SNL_18650_NCA_35C_0-100_0.5-1C_d
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        39.0:  # SNL_18650_NCA_35C_0-100_0.5-2C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        40.0:  # SNL_18650_NCA_35C_0-100_0.5-2C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is Li(Ni0.81Co0.14Al0.05)O2 (NCA811405). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is LG Chem. "
            f"The nominal capacity is 3.2 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.015625 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2.5 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        41.0:  # SNL_18650_NMC_15C_0-100_0.5-1C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 15 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        42.0:  # SNL_18650_NMC_15C_0-100_0.5-1C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 15 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        43.0:  # SNL_18650_NMC_15C_0-100_0.5-2C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 15 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        44.0:  # SNL_18650_NMC_15C_0-100_0.5-2C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 15 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        45.0:  # SNL_18650_NMC_25C_0-100_0.5-0.5C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 0.5 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        46.0:  # SNL_18650_NMC_25C_0-100_0.5-1C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        47.0:  # SNL_18650_NMC_25C_0-100_0.5-1C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        48.0:  # SNL_18650_NMC_25C_0-100_0.5-1C_c
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        49.0:  # SNL_18650_NMC_25C_0-100_0.5-1C_d
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        50.0:  # SNL_18650_NMC_25C_0-100_0.5-2C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        51.0:  # SNL_18650_NMC_25C_0-100_0.5-2C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        52.0:  # SNL_18650_NMC_25C_0-100_0.5-3C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        53.0:  # SNL_18650_NMC_25C_0-100_0.5-3C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        54.0:  # SNL_18650_NMC_25C_0-100_0.5-3C_c
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        55.0:  # SNL_18650_NMC_25C_0-100_0.5-3C_d
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 25 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 3 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        56.0:  # SNL_18650_NMC_35C_0-100_0.5-1C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        57.0:  # SNL_18650_NMC_35C_0-100_0.5-1C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        58.0:  # SNL_18650_NMC_35C_0-100_0.5-1C_c
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        59.0:  # SNL_18650_NMC_35C_0-100_0.5-1C_d
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 1 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        60.0:  # SNL_18650_NMC_35C_0-100_0.5-2C_a
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
        61.0:  # SNL_18650_NMC_35C_0-100_0.5-2C_b
            f"Battery specifications: The data comes from a lithium-ion battery in a format of 18650 cylindrical battery. "
            f"Its positive electrode is LiNi(0.84Co0.1Mn0.06)O2 (NCM840610). "
            f"Its negative electrode is graphite. "
            f"The electrolyte formula is unknown. "
            f"The battery manufacturer is Panasonic. "
            f"The nominal capacity is 3 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 35 degree Celsius. "
            f"In the cycling, the battery was charged at a constant current of 0.5 C until reaching 4.2 V, at which the battery was constant-voltage charged until the current dropped to 0.01667 C. "
            f"The battery was then discharged at a constant current of 2 C until reaching 2 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n",
    }