class Stanford_protocol_prompt():
    Protocols_prompts = {
        1.0:  # 100 Reference cell
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 25 degrees Celsius, the battery was first charged at 0.2 A to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.0552 A to 4.09 V and then charged at 0.0048 A to 4.4 V. "
            f"After that, a 1-hour constant voltage hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 72 hours. ",
        2.0:  ## 101 Reference cell
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 25 degrees Celsius, the battery was first charged at 0.2 A to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.0552 A to 4.09 V and then charged at 0.0048 A to 4.4 V. "
            f"After that, a 1-hour constant voltage hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 72 hours. ",
        3.0:  # 102 Reference cell
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 25 degrees Celsius, the battery was first charged at 0.2 A to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.0552 A to 4.09 V and then charged at 0.0048 A to 4.4 V. "
            f"After that, a 1-hour constant voltage hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 72 hours. ",
        4.0:  # 191
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 45 degrees Celsius, the battery was first charged at 0.2 C to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.0264 A to 3.71 V and then charged at 0.0048 A to 4.4 V. "
            f"After that, a 1-hour constant voltage (CV) hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"After the first formation cycle, 3 additional ±0.048 A cycles were performed between 3 and 4.4 V without CV hold or rest periods. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 72 hours. ",
        5.0:  # 192
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 45 degrees Celsius, the battery was first charged at 0.2 C to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.0264 A to 3.71 V and then charged at 0.0048 A to 4.4 V. "
            f"After that, a 1-hour constant voltage (CV) hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"After the first formation cycle, 3 additional ±0.048 A cycles were performed between 3 and 4.4 V without CV hold or rest periods. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 72 hours. ",
        6.0:  # 193
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 45 degrees Celsius, the battery was first charged at 0.2 C to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.1512 A to 3.74 V and then charged at 0.036 A to 4.4 V. "
            f"After that, a 1-hour constant voltage (CV) hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"After the first formation cycle, 2 additional ±0.048 A cycles were performed between 3 and 4.4 V without CV hold or rest periods. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 0 hour. ",
        7.0:  # 194
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 45 degrees Celsius, the battery was first charged at 0.2 C to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.1512 A to 3.74 V and then charged at 0.036 A to 4.4 V. "
            f"After that, a 1-hour constant voltage (CV) hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"After the first formation cycle, 2 additional ±0.048 A cycles were performed between 3 and 4.4 V without CV hold or rest periods. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 0 hour. ",
        8.0:  # 195
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 45 degrees Celsius, the battery was first charged at 0.2 C to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.1512 A to 3.74 V and then charged at 0.036 A to 4.4 V. "
            f"After that, a 1-hour constant voltage (CV) hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"After the first formation cycle, 2 additional ±0.048 A cycles were performed between 3 and 4.4 V without CV hold or rest periods. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 0 hour. ",
        9.0:  # 196
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 45 degrees Celsius, the battery was first charged at 0.2 C to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.3936 A to 3.62 V and then charged at 0.0216 A to 4.4 V. "
            f"After that, a 1-hour constant voltage (CV) hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"After the first formation cycle, 3 additional ±0.048 A cycles were performed between 3 and 4.4 V without CV hold or rest periods. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 72 hour. ",
        9.0:  # 198
            f"Battery specifications: The data comes from a lithium-ion battery in a format of pouch battery. "
            f"Its positive electrode is Li(Ni0.5Co0.2Mn0.3)O2 (NCM523). "
            f"Its negative electrode is artificial graphite. "
            f"The electrolyte formula consists of EC, EMC, DMC, and VC. The composition is 1 M LiPF6 in EC/EMC/DMC (1 : 1 : 1 by volume) solvent with 2% VC (by weight) additive. "
            f"The battery manufacturer is unknown. "
            f"The nominal capacity is 0.24 Ah. "
            f"Operating condition: The working history of this battery is just after formation. "
            f"The working ambient temperature of this battery is 30 degrees Celsius. "
            f"The battery was charged at a constant current of 1 C until reaching 4.4 V followed by a constant voltage hold to 0.05C. "
            f"The battery was then discharged at a constant current of 0.75 C until reaching 3.0 V. "
            f"The cycling state-of-charge of this battery ranges from 0% to 100%.\n"
            f"During formation, at 45 degrees Celsius, the battery was first charged at 0.2 C to 1.5 V and held for 24 hours. "
            f"Then, it was charged at 0.3936 A to 3.62 V and then charged at 0.0216 A to 4.4 V. "
            f"After that, a 1-hour constant voltage (CV) hold was applied at 4.4 V. "
            f"This was followed by a 0.048 A discharge to 3 V. "
            f"After the first formation cycle, 3 additional ±0.048 A cycles were performed between 3 and 4.4 V without CV hold or rest periods. "
            f"Finally, the battery was held at 3 V for 1 hour before being degassed and resealed in an Ar glove box. "
            f"Before cycling, the battery rested for 72 hour. ",

    }
